-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 10:47:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `Curso_nome` VARCHAR(45) NOT NULL,
  `Professor_id` VARCHAR(45) NOT NULL,
  `Professor_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`, `Curso_nome`, `Professor_id`, `Professor_nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT NOT NULL,
  `Turma_sala` VARCHAR(45) NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Curso_Curso_nome` VARCHAR(45) NOT NULL,
  `Curso_Professor_id` VARCHAR(45) NOT NULL,
  `Curso_Professor_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTurma`, `Turma_sala`, `Curso_idCurso`, `Curso_Curso_nome`, `Curso_Professor_id`, `Curso_Professor_nome`),
  INDEX `fk_Turma_Curso1_idx` (`Curso_idCurso` ASC, `Curso_Curso_nome` ASC, `Curso_Professor_id` ASC, `Curso_Professor_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`Curso_idCurso` , `Curso_Curso_nome` , `Curso_Professor_id` , `Curso_Professor_nome`)
    REFERENCES `mydb`.`Curso` (`idCurso` , `Curso_nome` , `Professor_id` , `Professor_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `idAlunos` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `Turma_idTurma` INT NOT NULL,
  `Turma_Turma_sala` VARCHAR(45) NOT NULL,
  `Turma_Curso_idCurso` INT NOT NULL,
  `Turma_Curso_Curso_nome` VARCHAR(45) NOT NULL,
  `Turma_Curso_Professor_id` VARCHAR(45) NOT NULL,
  `Turma_Curso_Professor_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlunos`, `Nome`, `Turma_idTurma`, `Turma_Turma_sala`, `Turma_Curso_idCurso`, `Turma_Curso_Curso_nome`, `Turma_Curso_Professor_id`, `Turma_Curso_Professor_nome`),
  INDEX `fk_Alunos_Turma1_idx` (`Turma_idTurma` ASC, `Turma_Turma_sala` ASC, `Turma_Curso_idCurso` ASC, `Turma_Curso_Curso_nome` ASC, `Turma_Curso_Professor_id` ASC, `Turma_Curso_Professor_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_Turma1`
    FOREIGN KEY (`Turma_idTurma` , `Turma_Turma_sala` , `Turma_Curso_idCurso` , `Turma_Curso_Curso_nome` , `Turma_Curso_Professor_id` , `Turma_Curso_Professor_nome`)
    REFERENCES `mydb`.`Turma` (`idTurma` , `Turma_sala` , `Curso_idCurso` , `Curso_Curso_nome` , `Curso_Professor_id` , `Curso_Professor_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instrutor` (
  `idInstrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrutor_has_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instrutor_has_Turma` (
  `Instrutor_idInstrutor` INT NOT NULL,
  `Turma_idTurma` INT NOT NULL,
  `Turma_Turma_sala` VARCHAR(45) NOT NULL,
  `Turma_Curso_idCurso` INT NOT NULL,
  `Turma_Curso_Curso_nome` VARCHAR(45) NOT NULL,
  `Turma_Curso_Professor_id` VARCHAR(45) NOT NULL,
  `Turma_Curso_Professor_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Instrutor_idInstrutor`, `Turma_idTurma`, `Turma_Turma_sala`, `Turma_Curso_idCurso`, `Turma_Curso_Curso_nome`, `Turma_Curso_Professor_id`, `Turma_Curso_Professor_nome`),
  INDEX `fk_Instrutor_has_Turma_Turma1_idx` (`Turma_idTurma` ASC, `Turma_Turma_sala` ASC, `Turma_Curso_idCurso` ASC, `Turma_Curso_Curso_nome` ASC, `Turma_Curso_Professor_id` ASC, `Turma_Curso_Professor_nome` ASC) VISIBLE,
  INDEX `fk_Instrutor_has_Turma_Instrutor1_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_Instrutor_has_Turma_Instrutor1`
    FOREIGN KEY (`Instrutor_idInstrutor`)
    REFERENCES `mydb`.`Instrutor` (`idInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instrutor_has_Turma_Turma1`
    FOREIGN KEY (`Turma_idTurma` , `Turma_Turma_sala` , `Turma_Curso_idCurso` , `Turma_Curso_Curso_nome` , `Turma_Curso_Professor_id` , `Turma_Curso_Professor_nome`)
    REFERENCES `mydb`.`Turma` (`idTurma` , `Turma_sala` , `Curso_idCurso` , `Curso_Curso_nome` , `Curso_Professor_id` , `Curso_Professor_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
